name: Java CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    name: build on jdk ${{matrix.jdk_version}}
    strategy:
      fail-fast: false
      matrix:
        jdk_version: [8, 11, 14]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up JDK ${{matrix.jdk_version}}
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.jdk_version}}
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          job-id: jdk${{matrix.jdk_version}}
          arguments: check --no-daemon --build-cache
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true